### ISSUE TITLE
the "how to pass data" guide has confusing code examples

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#130]
https://govuk-prototype-kit.herokuapp.com/docs/examples/pass-data

the "Showing answers in inputs " section has example code that doesn't include any GOV.UK Frontend classes

might be better to have full examples with GOVUK Frontend code

**Comment by hannalaakso** [comment]
On the basis of discussing this with the team we'd like to use the macros to generate the HTML for these examples so that it doesn't get out of sync with GOV.UK Frontend code. However if this isn't possible without spending more than the triaged 'hours' on this we should just hardcode the examples to use GOV.UK Frontend HTML.

**Comment by joelanman** [comment]
the examples now use macros, since #123
