### ISSUE TITLE
Navigation is broken

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#74]
On some pages the breadcrumbs and navigation menu links are all broken, for example:

https://govuk-prototype-kit.herokuapp.com/docs/make-first-prototype/use-components

https://govuk-prototype-kit.herokuapp.com/docs/install/run-the-kit

**Comment by lfdebrux** [comment]
This is because of changes made in #69 to use relative links. I didn't consider what it would mean having relative links in the [page layout template](https://github.com/alphagov/govuk-prototype-kit-docs/blob/main/docs/v12/views/layout.html) when URLs can have different levels of nesting.

I'll take a look at fixing this now.
